setores_por_ticker = {
    'ABEV3': 'Consumo Básico',
    'ALOS3': 'Saúde',
    'AMER3': 'Consumo Discricionário',
    'AMOB3': 'Outros',
    'ANIM3': 'Educação',
    'ASAI3': 'Consumo Básico',
    'AURE3': 'Mineração e Siderurgia',
    'AZEV4': 'Indústria e Bens de Capital',
    'AZUL4': 'Consumo Discricionário',
    'B3SA3': 'Bolsas e Serviços Financeiros',
    'BBAS3': 'Bancos',
    'BBDC3': 'Bancos',
    'BBDC4': 'Bancos',
    'BBSE3': 'Seguradoras',
    'BEEF3': 'Agronegócio',
    'BHIA3': 'Consumo Discricionário',
    'BPAC11': 'Bancos',
    'BRAP4': 'Mineração e Siderurgia',
    'BRAV3': 'Outros',
    'BRFS3': 'Agronegócio',
    'BRKM5': 'Mineração e Siderurgia',
    'CBAV3': 'Mineração e Siderurgia',
    'CCRO3': 'Indústria e Bens de Capital',
    'CEAB3': 'Consumo Discricionário',
    'CMIG4': 'Energia Elétrica',
    'CMIN3': 'Mineração e Siderurgia',
    'COGN3': 'Educação',
    'CPLE3': 'Energia Elétrica',
    'CPLE6': 'Energia Elétrica',
    'CRFB3': 'Consumo Básico',
    'CSAN3': 'Petróleo, Gás e Biocombustíveis',
    'CSED3': 'Saúde',
    'CSMG3': 'Utilidades Públicas',
    'CSNA3': 'Mineração e Siderurgia',
    'CURY3': 'Indústria e Bens de Capital',
    'CVCB3': 'Consumo Discricionário',
    'CXSE3': 'Bancos',
    'CYRE3': 'Indústria e Bens de Capital',
    'DIRR3': 'Indústria e Bens de Capital',
    'DXCO3': 'Consumo Discricionário',
    'ECOR3': 'Indústria e Bens de Capital',
    'ELET3': 'Energia Elétrica',
    'ELET6': 'Energia Elétrica',
    'EMBR3': 'Indústria e Bens de Capital',
    'ENEV3': 'Energia Elétrica',
    'ENGI11': 'Energia Elétrica',
    'EQTL3': 'Energia Elétrica',
    'EZTC3': 'Indústria e Bens de Capital',
    'FLRY3': 'Saúde',
    'GFSA3': 'Indústria e Bens de Capital',
    'GGBR4': 'Mineração e Siderurgia',
    'GGPS3': 'Indústria e Bens de Capital',
    'GMAT3': 'Consumo Discricionário',
    'GOAU4': 'Mineração e Siderurgia',
    'GOLL4': 'Consumo Discricionário',
    'GRND3': 'Consumo Discricionário',
    'HAPV3': 'Saúde',
    'HBSA3': 'Saúde',
    'HYPE3': 'Saúde',
    'IFCM3': 'Outros',
    'IGTI11': 'Tecnologia',
    'INTB3': 'Saúde',
    'IRBR3': 'Seguradoras',
    'ISAE4': 'Outros',
    'ITSA4': 'Bancos',
    'ITUB4': 'Bancos',
    'JBSS3': 'Agronegócio',
    'JHSF3': 'Consumo Discricionário',
    'KEPL3': 'Indústria e Bens de Capital',
    'KLBN11': 'Papel e Celulose',
    'KLBN4': 'Papel e Celulose',
    'LIGT3': 'Energia Elétrica',
    'LJQQ3': 'Consumo Discricionário',
    'LREN3': 'Consumo Discricionário',
    'LWSA3': 'Tecnologia',
    'MGLU3': 'Consumo Discricionário',
    'MOVI3': 'Consumo Discricionário',
    'MRFG3': 'Agronegócio',
    'MRVE3': 'Indústria e Bens de Capital',
    'MULT3': 'Consumo Discricionário',
    'NEOE3': 'Energia Elétrica',
    'NTCO3': 'Consumo Discricionário',
    'OIBR3': 'Comunicação',
    'PCAR3': 'Consumo Básico',
    'PETR3': 'Petróleo, Gás e Biocombustíveis',
    'PETR4': 'Petróleo, Gás e Biocombustíveis',
    'PETZ3': 'Consumo Discricionário',
    'PMAM3': 'Mineração e Siderurgia',
    'POMO4': 'Indústria e Bens de Capital',
    'PRIO3': 'Petróleo, Gás e Biocombustíveis',
    'PSSA3': 'Seguradoras',
    'QUAL3': 'Saúde',
    'RADL3': 'Saúde',
    'RAIL3': 'Indústria e Bens de Capital',
    'RAIZ4': 'Consumo Discricionário',
    'RAPT4': 'Indústria e Bens de Capital',
    'RCSL4': 'Outros',
    'RDOR3': 'Saúde',
    'RECV3': 'Petróleo, Gás e Biocombustíveis',
    'RENT3': 'Consumo Discricionário',
    'SANB11': 'Bancos',
    'SBSP3': 'Utilidades Públicas',
    'SIMH3': 'Saúde',
    'SLCE3': 'Agronegócio',
    'SMFT3': 'Saúde',
    'SRNA3': 'Outros',
    'STBP3': 'Indústria e Bens de Capital',
    'SUZB3': 'Papel e Celulose',
    'TAEE11': 'Energia Elétrica',
    'TEND3': 'Indústria e Bens de Capital',
    'TIMS3': 'Comunicação',
    'TOTS3': 'Tecnologia',
    'TUPY3': 'Indústria e Bens de Capital',
    'UGPA3': 'Petróleo, Gás e Biocombustíveis',
    'USIM5': 'Mineração e Siderurgia',
    'VALE3': 'Mineração e Siderurgia',
    'VAMO3': 'Indústria e Bens de Capital',
    'VBBR3': 'Outros',
    'VIVA3': 'Saúde',
    'VIVT3': 'Comunicação',
    'WEGE3': 'Indústria e Bens de Capital',
    'YDUQ3': 'Educação',
}
